name: build-and-test

on:
  push:
    # all branches
    paths-ignore:
      - 'documentation/**'
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - 'documentation/**'

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Install Opendylan compiler
        uses: dylan-lang/install-opendylan@v3

      - name: Install dependencies
        run: dylan update

      - name: Build testworks-test-suite-app
        run: dylan build testworks-test-suite-app

      - name: Run testworks-test-suite-app
        run: |
          _build/bin/testworks-test-suite-app --report surefire --report-file _build/TEST-testworks.xml

      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/_build/TEST-*.xml'
